### ISSUE TITLE
TC_GZip::compress在输入长度为0时的内存泄漏问题

### ISSUE THREAD

**Issue by jacobwpeng** [TarsCloud/TarsCpp#103]
bool TC_GZip::compress(const char *src, size_t length, vector<char>& buffer);

当length=0时，destLen = sizeof(gz_simple_header);
在memcpy完gz_simple_header后， stream.avail_out=0，deflate返回错误码Z_BUF_ERROR，此时只进行了delete []out; 没有执行deflateEnd(&stream); 导致deflateInit2中分配的内存泄漏。

destLen应该为 sizeof(gz_simple_header) + compressBound(&stream, length);

**Comment by ruanshudong** [comment]
感谢, bug fix, thx! 以后这类问题, 你可以改了, 提交一个pr上来, 留一个痕迹:)
