### ISSUE TITLE
关于使用Docker部署如何创建服务

### ISSUE THREAD

**Issue by mansoncode** [TarsCloud/TarsCpp#105]
已经使用docker部署了tars，但是应该如何创立服务。使用/usr/local/tars/cpp/script/cmake_tars_server.sh，里面没有这个sh文档。

**Comment by ruanshudong** [comment]
你得编译tarscpp源码, 这个编译make;make install以后会有tarscpp的库, 才会有这个工具, 基于这个lib库写你的服务
