### ISSUE TITLE
如何判断服务是否上线

### ISSUE THREAD

**Issue by ricklii** [TarsCloud/TarsCpp#106]
通信器获得代理：
Application::getCommunicator()->setProperty("locator", "tars.tarsregistry.QueryObj@tcp -h 172.25.1.10 -p 17890 -t 10000");
Application::getCommunicator()->stringToProxy("MicroXXX.YServer.ZObj", myYPrx);

如何判断myYPrx是否已上线？

尝试使用myYPrx->getEndpoint().empty()来判断，似乎不行，程序直接SIGSEGV退出了

tars版本2.4.3

**Comment by ricklii** [comment]
补充下，如果myYPrx已经在线的情况下，myYPrx->getEndpoint()能正常判断；不在线，会直接SIGSEGV出错

**Comment by ruanshudong** [comment]
myYPrx->tars_ping(), 但是这个调用是同步的

**Comment by ricklii** [comment]
@ruanshudong 好的，非常感谢，我暂时考虑的就是同步的。不过建议能增加异步的方式

**Comment by ruanshudong** [comment]
正常返回,不抛异常, 就表示服务已经启动, 并且能接受请求了, 你用的哪个版本的tarscpp ?

**Comment by ricklii** [comment]
最近的一个版本，应该是2.4.3

**Comment by ruanshudong** [comment]
建议升级一个版本, 这个版本发现了一个bug, 应该正好影响: myYPrx->getEndpoint()

**Comment by ricklii** [comment]
好的，感谢
