### ISSUE TITLE
新版本服务发现功能不正常

### ISSUE THREAD

**Issue by ricklii** [TarsCloud/TarsCpp#127]
旧版本（v2.4.3）只需要: comm.stringToProxy("TestApp.HelloServer.HelloObj")即可, 框架会自动寻址后端的HelloServer服务

前几天更新了最新版2.4.11，发现必须要指定ip:port，即comm.stringToProxy("TestApp.HelloServer.HelloObj@tcp -h 10.120.129.226 -p 20001" , prx)，才能调用服务

即使部署在框架上，也存在这个问题

**Comment by ruanshudong** [comment]
tarscpp更新到v2.4.12看看, 2.4.11确实发了一个bug

**Comment by ricklii** [comment]
更新了2.4.12，问题还是存在啊，服务发现不了

**Comment by ruanshudong** [comment]
你框架是怎么部署的, 用什么版本?

**Comment by ruanshudong** [comment]
如何, 是否还有问题?

**Comment by ricklii** [comment]
部署在docker上，框架、程序都用的2.4.12，还是有问题

你们开发测试是正常的吗

**Comment by ruanshudong** [comment]
新版本好像没有发现问题, 你加我qq: 39067484

**Comment by ruanshudong** [comment]
找到bug了, 尽快修复一下, web有bug导致的

**Comment by ruanshudong** [comment]
修改这个bug了, 更新了web, 可以更新web试一试, 或者直接用v2.4.11这个docker
