### ISSUE TITLE
请问可不可以默认不要构建examples目录的内容

### ISSUE THREAD

**Issue by jarod** [TarsCloud/TarsCpp#136]
估计大部分构建TarsFramework的同学都不会用到examples。默认不要构建examples，增加一个`make examples`命令，这个可以为地球节省很多能源

**Comment by ETZhangSX** [comment]
可以直接注释 `CMakeLists.txt` 中的 `add_subdirectory(examples)`

**Comment by ruanshudong** [comment]
这个问题, 下个版本改一下
