### ISSUE TITLE
异常上报宏接口无效

### ISSUE THREAD

**Issue by ETZhangSX** [TarsCloud/TarsCpp#141]
下面这三个异常上报接口无效，TarsWeb 没有显示，而 `RemoteNotify::report` 接口有效。看了实现，区别在 `eType` 字段值为 `REPORT` 还是 `NOTIFY`，看了实现，`switch` 语句中的 `NOTIFY` 部分没有上报逻辑，同时还发现 `REPORT` 部分每次上报都会打一次 `ERROR` 日志。

```cpp
//上报普通信息
TARS_NOTIFY_NORMAL(info) 
//上报警告信息
TARS_NOTIFY_WARN(info) 
//上报错误信息
TARS_NOTIFY_ERROR(info)
```

TarsGo 中修复了这个问题，其实就是把 `eType` 改为 `REPORT`，不使用 `NOTIFY` 类型。想知道 `NOTIFY` 的设计是有什么考虑？

**Comment by ruanshudong** [comment]
最早设计上report是给框架内部自身用, notify是给业务使用TARS_NOTIFY_***宏来使用, 框架的report会写到db中, web上展示, notify只是记录了tarsnotify的日志, 监控脚本扫描db触发告警, 这个数据并没有写到db中, 因为业务使用的方式不可控, 如果批量发, 会把db写爆

**Comment by ruanshudong** [comment]
等后面k8s版本搞完, 计划notify, stat的数据都会写入到es中, 就不存在这个问题了
