### ISSUE TITLE
xxx.tars文件中2个enum类型含有相同的成员，生成的xxx.h文件编译会报错："error: redeclaration of xxx"

### ISSUE THREAD

**Issue by PGMay** [TarsCloud/TarsCpp#15]
xxx.tars文件中2个enum类型含有相同的成员，生成的xxx.h文件编译会报错："error: redeclaration of xxx"

生成文件后需要手工改enum的命名空间。

**Comment by helloopenworld** [comment]
目前还不支持enum的成员用命令空间来区别，也就是不支持不同的enum有定义相同的成员。
