### ISSUE TITLE
异常里的函数名有误

### ISSUE THREAD

**Issue by tzwsoho** [TarsCloud/TarsCpp#151]
https://github.com/TarsCloud/TarsCpp/blob/29b0107ce979e974c05f28210b32b1ab4d781113/util/src/tc_bitmap.cpp#L248
https://github.com/TarsCloud/TarsCpp/blob/29b0107ce979e974c05f28210b32b1ab4d781113/util/src/tc_bitmap.cpp#L260
https://github.com/TarsCloud/TarsCpp/blob/29b0107ce979e974c05f28210b32b1ab4d781113/util/src/tc_bitmap.cpp#L272

函数名有误

**Comment by ruanshudong** [comment]
确实, 提交一个pr?

**Comment by tzwsoho** [comment]
> 确实, 提交一个pr?

ok，已提交
