### ISSUE TITLE
TC_HttpRequest，是否支持https协议？我试了一下，好像是不行的

### ISSUE THREAD

**Issue by hilberthu** [TarsCloud/TarsCpp#162]
TC_HttpRequest stReq;
    stReq.setPostRequest(strUrl, strBody);
    stReq.setCookie(strCookies);
    TC_HttpAsync::RequestCallbackPtr p = new AsyncHttpCallback(strUrl, nUuid);
    m_httpAsync.doAsyncRequest(stReq, p, false);
如果这里的strUrl是https协议的，会有问题，请问有没有计划支持https呢

**Comment by ruanshudong** [comment]
用http_call, 那个支持https

**Comment by hilberthu** [comment]
谢谢
