### ISSUE TITLE
纯客户端如何使用协程？

### ISSUE THREAD

**Issue by zz-mars** [TarsCloud/TarsCpp#20]
我参考ServantHandle::run()里main协程方式的实现写的纯客户端使用协程的代码，不知道对不对，有没有官方的代码示例？

`CoroutineScheduler * g_coroSched = NULL;
const static uint32_t g_coroPoolSz = 1024 * 1024;
const static size_t g_coroStackSz = 128 * 1024;

void doSomething() {
    while(true) {
        // do something    
    }
}
static void initCoro() {
    g_coroSched = new CoroutineScheduler();
    g_coroSched->init(g_coroPoolSz, g_coroStackSz);
    g_coroSched->createCoroutine(doSomething);
    ServantProxyThreadData * pSptd = ServantProxyThreadData::getData();
    pSptd->_sched = g_coroSched;
    g_coroSched->run();
}

int main() {
    initCoro();
    return 0;
}`

**Comment by surejammy** [comment]
我看example里有：
串行：
examples\CoroutineDemo\testCoro

并行：
examples\CoroutineDemo\testParallelCoro
