### ISSUE TITLE
v1.0一点小问题

### ISSUE THREAD

**Issue by 6923403** [TarsCloud/TarsCpp#208]
```
/root/git/TarsCpp/servant/libservant/Transceiver.cpp:23:10: fatal error: servant/Auth.h: 没有那个文件或目录
   23 | #include "servant/Auth.h"
```

应该是AuthF.h了

**Comment by ruanshudong** [comment]
啥版本?

**Comment by 6923403** [comment]
最初的版本 v1.0.0  好像0.1 0.2也不行 你点分支选tags  在2021年12月18日 20:51，ruanshudong 写道： 

啥版本?



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you authored the thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/TarsCloud/TarsCpp/issues/208#issuecomment-997198321",

"url": "https://github.com/TarsCloud/TarsCpp/issues/208#issuecomment-997198321",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by 6923403** [comment]
> 啥版本?

v1.0.0

 0.1 0.2好像也得改下

**Comment by ruanshudong** [comment]
版本太老了, 干嘛不升级到2.4最后一个版本

**Comment by 6923403** [comment]
> 版本太老了, 干嘛不升级到2.4最后一个版本

就自己没事看看源码， 那我换到release2.4的分支去
