### ISSUE TITLE
你好，使用ServantPrx做客户端，怎样可以接收服务端主动发来的消息

### ISSUE THREAD

**Issue by sunxiao2010n** [TarsCloud/TarsCpp#209]
在使用ServantPrx连接服务端时，都是由ServantPrx发出请求并拿到对方回应，请问有什么好办法，即使不发送请求，也能接收对端消息呢？

**Comment by ruanshudong** [comment]
这个好像没办法支持, 不发请求, 连接都不会建立, 就不可能收到响应

**Comment by shevqko** [comment]
完全不发请求不行，如果只是不想发业务请求， 可以发个 tars_ping() 请求？

**Comment by sunxiao2010n** [comment]
也就是说，目前并不支持由服务器主动向客户端发请求，需要双方都连接对方的servant对吗

**Comment by ruanshudong** [comment]
客户端都没有发起连接, 服务器怎么向客户端发请求呢?

**Comment by sunxiao2010n** [comment]
您好！已建连，现在由服务器发给客户端消息，怎么发送呀

**Comment by ruanshudong** [comment]
可以参考: https://doc.tarsyun.com/#/dev/tarscpp/tars_push.md
不过目前是必须要先客户端发一个请求上来才行

**Comment by sunxiao2010n** [comment]
谢谢您提供的信息，十分感谢

**Comment by sunxiao2010n** [comment]
好的，谢谢您提供的信息
