### ISSUE TITLE
请问 ： “CommunicatorEpoll::run()”  为啥要在一个 协程上下文中调用?  

### ISSUE THREAD

**Issue by triump2020** [TarsCloud/TarsCpp#222]
在 `TC_Thread::coroutineEntry`  中   会调用  `pThread->_scheduler->go(std::bind(TC_Thread::threadEntry, pThread));`  ：即CommunicatorEpoll::run 函数会再一个协程的环境中运行， 为什么?

**Comment by ruanshudong** [comment]
代码看这么细?这样做可以使得通信器网络部分和服务器网络部分能在一个线程中混合运行!!

**Comment by triump2020** [comment]
谢谢大神! 协程这块我还没看清楚，现在还不能理解.

**Comment by ruanshudong** [comment]
提示几点吧:
1 协程的调度是阻塞在epoller上,即通过epoller的唤醒来调度和切换协程
2 网络事件的调度也是通过epoller
这样可以把协程调度和网络调度混合到一起, 从而在3.0版本中, 通信器的线程也服务器端的业务线程/网络线程, 都可以公用了(因为都通过epoller来触发的), 这是核心, 看懂这个, 其他就相对容易理解了.

**Comment by triump2020** [comment]
谢谢！

**Comment by triump2020** [comment]
明白了。 在3.0 中， 通信器的线程和服务端的网络IO 线程，业务处理线程 可以合并为一个线程，这个线程里面用epoller 实现了协程的调度?

**Comment by ruanshudong** [comment]
是
