### ISSUE TITLE
请问下：关于stringToProxy() 函数的 向下转型问题?

### ISSUE THREAD

**Issue by triump2020** [TarsCloud/TarsCpp#227]
Hi , 请问下 在stringToProxy() 函数中，其实是new 了一个 父类对象:ServantProxy,  然后将这个父类对象指针向下转型成子类对象指针,然后调用子类里面的方法?   正常来讲，这种做法不对。 但这样做的前提是： 工具生成的子类(比如HelloProxy)里没有非静态数据成员， 请问我理解对么?   谢谢!
![image](https://user-images.githubusercontent.com/63033222/157834800-ba409000-1e6b-477d-8d08-edf6a8784276.png)

**Comment by ruanshudong** [comment]
yes
