### ISSUE TITLE
【tarslog】想问下按一定频率记日志怎么实现的？

### ISSUE THREAD

**Issue by libo1712** [TarsCloud/TarsCpp#253]
RemoteLogger.h中有这样一段
   /**
     * 初始化设置时间格式("%Y%m%d")
     * 不要动态修改, 线程不安全
     * 如果有需要, 初始化后直接修改
     * @param sFormat, 文件名称, 为空表示缺省的时间日志
     * @param frequency 支持每多少天/小时/分钟，详见TC_logger.h中关于TarsLogByDay,TarsLogByHour,TarsLogByMinute的描述
     *
     * 用法: 按两个小时记录日志
     * initFormat<TarsLogByHour>("logfile",TarsLogByHour::FORMAT,2);
     */
    template<class TLogType>
    void initFormatWithType(const string &sFile, const string &sFormat,size_t frequency)
    {
        LogTypePtr logTypePtr = new TLogType(sFormat,frequency);
        initFormat(sFile,sFormat,logTypePtr);
    }

    template<class TLogType>
    void initFormatWithType(const string &sApp, const string &sServer,const string &sFile, const string &sFormat,size_t frequency)
    {
        LogTypePtr logTypePtr = new TLogType(sFormat,frequency);
        initFormat(sApp,sServer,sFile,sFormat,logTypePtr);
    }
但是自己在调用时一直报错，没有实现。 
还请指教

**Comment by ruanshudong** [comment]
你代码怎么写? 贴出来看看

**Comment by libo1712** [comment]
比如想两分钟记次日志，我按照RemoteLogger.h中的定义在初始化完这样写的：
RemoteTimeLogger::getInstance()->initFormatWithType("","%Y%m%d%H%M", 2);

编译会报错，能给个简单的demo么，谢谢大神

**Comment by libo1712** [comment]
我没看到模板类，这样写就对了 
RemoteTimeLogger::getInstance()->initFormatWithType<LogByMinute>("","%Y%m%d%H%M", 2);
建议把RemoteLogger.h中的注释稍微改下
