### ISSUE TITLE
Exception: autoptr null handle error![N4tars12CommunicatorE]

### ISSUE THREAD

**Issue by duansumin2022** [TarsCloud/TarsCpp#290]
TARS_VERSION:              3.0.1

client rpc调用的时候抛出异常（非必现异常，偶发异常）：Exception: autoptr null handle error![N4tars12CommunicatorE]
业务prx rpc调用抛异常

**Comment by BeyondWUXF** [comment]
好像是没创建Communicator

**Comment by duansumin2022** [comment]
> 好像是没创建Communicator

通过 new tars::Communicator(); 创建的Communicator，然后把_comm 传给sdkAgent，在sdkAgent的init里面，通过_comm创建SDKServantPrx：
`
tars::Communicator* _comm = new tars::Communicator();
    ....
sdkAgent = new SDKAgent ();
sdkAgent ->init(_comm);
`
`
int SDKAgent ::init(Communicator* comm){
...
comm->stringToProxy(serverObjName , prx); // typedef tars::TC_AutoPtr<SDKServantProxy> SDKServantPrx;
...
}
`
是不是Communicator使用的方式，或者prx服务句柄的获取方式不对呢？

**Comment by BeyondWUXF** [comment]
typedef tars::TC_AutoPtr<SDKServantProxy> SDKServantPrx;
应该是这样吧

**Comment by BeyondWUXF** [comment]
typedef tars::TC_AutoPtr<SDKServant> SDKServantPrx;
应该是这样吧

**Comment by BeyondWUXF** [comment]
typedef tars::TC_AutoPtr<SDKServant***> SDKServantPrx;应该这样吧

**Comment by duansumin2022** [comment]
> typedef tars::TC_AutoPtr<SDKServant***> SDKServantPrx;应该这样吧

是这样的，上一条好像没有显示出来。

**Comment by ruanshudong** [comment]
最新版已经修复了吧?用最新版本试一试

**Comment by ruanshudong** [comment]
应该是最新的tag版本才发现和修复这个问题

**Comment by ruanshudong** [comment]
https://github.com/TarsCloud/TarsCpp/commit/3b90fd870d13a947a2232b8d2ddf4ef5cfd07836
应该是这个修改的

**Comment by duansumin2022** [comment]
> [3b90fd8](https://github.com/TarsCloud/TarsCpp/commit/3b90fd870d13a947a2232b8d2ddf4ef5cfd07836) 应该是这个修改的

这个修改是RemoteTimeLogger，我的应用是纯客户端，是一个tars server 的 client SDK，没有开启远程日志。而且在 new tars::Communicator() 后，有判断comm是创建成功了。 在通过prx （SDKServantPrx）调用与server的接口函数时try catch 捕获到的异常：

```
	try
	{
               int ret = prx->get(req, rsp); //与server的接口函数
		if(ret!=0) {
                        cout<<"ret:"<<ret<<" failed !"<<endl;
			return ret;
		}
               cout<<"ret:"<<ret<<" seccess !"<<endl;
	}
	catch (std::exception &e)
	{
		cout << "Exception: " << e.what() << endl;    //  这里捕获到 autoptr null handle error![N4tars12CommunicatorE]
		TLOGERROR(MessageIDKit::Log() << "Exception|" << e.what() << std::endl);  //  这里捕获到 autoptr null handle error![N4tars12CommunicatorE]
		return -1;
	}
	catch (...)
	{
		cout << "unknown exception" << endl;
		return -1;
	}
```
