### ISSUE TITLE
管理平台无法发布程序

### ISSUE THREAD

**Issue by hypeaches** [TarsCloud/TarsCpp#31]
按照Install.zh.md的安装步骤，安装完成后，登录管理平台，发布一个测试服务EchoServer，但是“设置状态”为Active，当前状态为Off，发布服务其实也是失败的
![图片](https://user-images.githubusercontent.com/35215878/65385456-7bcb5480-dd61-11e9-902e-aa8f72d4bca2.png)
求助怎么办？

**Comment by KatharineOzil** [comment]
是否方便贴一下日志？

**Comment by ruanshudong** [comment]
可以升级到新的框架和web管理平台, 发布错误的原因目前可以在服务管理页面看到了
