### ISSUE TITLE
AuthF.h不存在

### ISSUE THREAD

**Issue by wincsb** [TarsCloud/TarsCpp#46]
Scanning dependencies of target tarsservant
[ 47%] Building CXX object tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/AdapterProxy.cpp.o
In file included from /home/wincsb/Tars/framework/tarscpp/servant/servant/AdapterProxy.h:23:0,
                 from /home/wincsb/Tars/framework/tarscpp/servant/libservant/AdapterProxy.cpp:17:
/home/wincsb/Tars/framework/tarscpp/servant/servant/EndpointInfo.h:22:19: fatal error: AuthF.h: No such file or directory
 #include "AuthF.h"
                   ^

**Comment by xy2Git** [comment]
你好，我下载代码后也遇到了此问题，请问您是怎么解决的呢？

**Comment by ruanshudong** [comment]
是不是submodule没有下载, 需要 git clone xxxx  --recursive

**Comment by xy2Git** [comment]
> 是不是submodule没有下载, 需要 git clone xxxx --recursive


感谢，确实如此，原谅我不知道还有这种用法
